"""
Backtest engine — daily event loop simulating live trading.

Architecture
------------
For each trading day t:
1. Check open positions for stop-loss / take-profit exits  (use open price)
2. Generate signals from pre-computed model probabilities
3. Enter new positions for top buy signals               (use open price + slippage)
4. Record end-of-day equity using closing prices

Strict no-lookahead: signals on day t use features computed from data
through day t-1 only. Entry price is day t's open (or close of t-1 + slip).

NOTE: This is a vectorised daily simulation, not a true tick-level engine.
For production use, replace with an event-driven framework (e.g. Zipline, bt).
"""
import logging
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

from config import BacktestConfig, PortfolioConfig, SignalConfig
from portfolio.manager import PortfolioManager
from portfolio.sizing import PositionSizer
from signals.generator import SignalGenerator, SignalType

logger = logging.getLogger(__name__)


class BacktestEngine:
    """
    Daily backtest simulation.

    Usage:
        engine = BacktestEngine(bt_cfg, port_cfg, sig_cfg)
        equity_curve, trades = engine.run(probabilities, price_data, spy_df)
    """

    def __init__(
        self,
        bt_cfg: BacktestConfig,
        port_cfg: PortfolioConfig,
        sig_cfg: SignalConfig,
    ):
        self.bt_cfg = bt_cfg
        self.port_cfg = port_cfg
        self.sig_cfg = sig_cfg

    def run(
        self,
        probabilities: pd.DataFrame,
        price_data: Dict[str, pd.DataFrame],
        spy_df: Optional[pd.DataFrame] = None,
    ) -> Tuple[pd.Series, pd.DataFrame]:
        """
        Run backtest.

        Parameters
        ----------
        probabilities : DataFrame with DatetimeIndex; columns = ticker symbols;
                        values = model probability for that date/ticker.
                        Generated by Predictor.predict_history() per ticker.
        price_data    : OHLCV dict {ticker: DataFrame}
        spy_df        : Benchmark OHLCV (for regime gating)

        Returns
        -------
        equity_curve : pd.Series (DatetimeIndex) — daily portfolio value
        trades_df    : pd.DataFrame — completed trade log
        """
        from features.regime import MarketRegime

        # Build regime object if SPY data available
        regime = MarketRegime(spy_df) if spy_df is not None else None
        sig_gen = SignalGenerator(self.sig_cfg, regime)
        sizer = PositionSizer(self.port_cfg)
        portfolio = PortfolioManager(self.port_cfg)

        # Get common trading dates in backtest window
        dates = self._get_trading_dates(price_data)
        equity_curve: Dict[pd.Timestamp, float] = {}

        logger.info(
            "Starting backtest: %s → %s (%d days, capital=%.0f)",
            dates[0].date(), dates[-1].date(), len(dates), self.port_cfg.initial_capital
        )

        for date in dates:
            # Current prices (closing prices of this day)
            prices = self._get_prices_on(price_data, date, "Close")
            open_prices = self._get_prices_on(price_data, date, "Open")

            # 1. Check exits using open price (conservative)
            portfolio.update_exits(date, open_prices, self.bt_cfg.commission_pct)

            # 2. Exit positions with strong sell signal
            if date in probabilities.index:
                day_probs = probabilities.loc[date].dropna()
                for ticker in list(portfolio.positions.keys()):
                    if ticker in day_probs:
                        prob = day_probs[ticker]
                        if prob < self.sig_cfg.strong_sell_threshold:
                            price = open_prices.get(ticker, prices.get(ticker))
                            if price:
                                portfolio.exit_position(ticker, date, price, "signal_sell", self.bt_cfg.commission_pct)

            # 3. Generate buy signals and enter new positions
            if date in probabilities.index and len(portfolio.positions) < self.port_cfg.max_positions:
                day_probs = probabilities.loc[date].dropna()
                prob_dict = {t: float(p) for t, p in day_probs.items() if t not in portfolio.positions}

                signals = sig_gen.generate(prob_dict, price_data, date)
                buy_signals = sig_gen.top_buys(
                    signals,
                    n=self.port_cfg.max_positions - len(portfolio.positions),
                    min_type=SignalType.WEAK_BUY,
                )

                for sig in buy_signals:
                    ticker = sig.ticker
                    entry_price = open_prices.get(ticker, prices.get(ticker))
                    if entry_price is None or entry_price <= 0:
                        continue

                    # Apply slippage to entry
                    entry_price *= (1 + self.bt_cfg.slippage_pct)

                    n_shares = sizer.shares(
                        ticker, sig.probability,
                        price_data[ticker],
                        portfolio.equity,
                        len(portfolio.positions),
                        current_price=entry_price,
                    )
                    portfolio.enter(
                        ticker, date, entry_price, n_shares,
                        sig.probability, self.bt_cfg.commission_pct
                    )

            # 4. Record end-of-day equity
            equity_curve[date] = portfolio.mark_to_market(prices)

        equity_series = pd.Series(equity_curve, name="equity")
        trades_df = portfolio.trade_summary()

        # Close any remaining open positions at last available price
        for ticker in list(portfolio.positions.keys()):
            price = prices.get(ticker)
            if price:
                portfolio.exit_position(ticker, dates[-1], price, "end_of_backtest")

        logger.info("Backtest complete: %d trades, final equity=%.0f",
                    len(portfolio.trade_history), equity_series.iloc[-1] if len(equity_series) > 0 else 0)
        return equity_series, trades_df

    # ------------------------------------------------------------------

    def _get_trading_dates(self, price_data: Dict[str, pd.DataFrame]) -> pd.DatetimeIndex:
        """Get sorted trading dates within the backtest window."""
        all_dates = set()
        for ticker, df in price_data.items():
            all_dates.update(df.index.tolist())
        all_dates = pd.DatetimeIndex(sorted(all_dates))

        start = pd.Timestamp(self.bt_cfg.start_date)
        end = pd.Timestamp(self.bt_cfg.end_date)
        return all_dates[(all_dates >= start) & (all_dates <= end)]

    @staticmethod
    def _get_prices_on(
        price_data: Dict[str, pd.DataFrame],
        date: pd.Timestamp,
        col: str = "Close",
    ) -> Dict[str, float]:
        prices: Dict[str, float] = {}
        for ticker, df in price_data.items():
            if date in df.index:
                val = df.loc[date, col]
                if pd.notna(val):
                    prices[ticker] = float(val)
            else:
                # Use last known price
                before = df[df.index <= date]
                if len(before) > 0:
                    val = before[col].iloc[-1]
                    if pd.notna(val):
                        prices[ticker] = float(val)
        return prices
